### ISSUE TITLE
greatherThanOrEquals() Typo?

### ISSUE THREAD

**Issue by jianjye** [spryker/decimal-object#16]
Hi. Thank you for the great package. 

I noticed that there is an extra "h" in the `greatherThanOrEquals()` function. By right it should be `greaterThanOrEquals()`. 

It's not a big issue. Just thought I'd let you know anyway. :) 

Thanks again.

**Comment by dereuromark** [comment]
Feel free to make a PR to fix this, including keeping the old method but deprecating it.

**Comment by dereuromark** [comment]
@jianjye Can you check if https://github.com/spryker/decimal-object/pull/17 solves it?
